import Ingredient from '../models/Ingredient.js';
import StockLog from '../models/StockLog.js';
import PurchaseOrder from '../models/PurchaseOrder.js';
import Business from '../models/Business.js';

// Deducts the ingredients consumed by a sold order's items (per each
// product's recipe) and auto-creates a purchase order for any ingredient
// that drops below its reorder threshold as a result.
export async function consumeRecipeForItems(items, { businessId, tokenId, createdBy }) {
  const business = await Business.findById(businessId);
  const autoCreatePO = business?.settings?.autoCreatePurchaseOrder ?? true;

  // items: populated Token.items, each with product.recipe
  const usage = new Map(); // ingredientId -> qty consumed

  for (const item of items) {
    const recipe = item.product?.recipe || [];
    for (const line of recipe) {
      const ingId = String(line.ingredient);
      usage.set(ingId, (usage.get(ingId) || 0) + line.qty * item.qty);
    }
  }

  for (const [ingredientId, qtyUsed] of usage.entries()) {
    const ingredient = await Ingredient.findById(ingredientId);
    if (!ingredient) continue;

    ingredient.stockQty = Math.max(0, ingredient.stockQty - qtyUsed);
    await ingredient.save();

    await StockLog.create({
      ingredient: ingredient._id,
      type: 'consumption',
      qtyChange: -qtyUsed,
      token: tokenId,
      createdBy,
    });

    if (autoCreatePO && ingredient.stockQty <= ingredient.thresholdQty) {
      const existingPending = await PurchaseOrder.findOne({
        ingredient: ingredient._id,
        status: 'pending',
        autoGenerated: true,
      });
      if (!existingPending) {
        await PurchaseOrder.create({
          ingredient: ingredient._id,
          qtyOrdered: ingredient.reorderQty || ingredient.thresholdQty * 2 || 1,
          autoGenerated: true,
          createdBy,
        });
      }
    }
  }
}

// Restores stock when an order is cancelled before the kitchen has consumed
// the ingredients in any irreversible way (best-effort, mirrors the deduction).
export async function restockRecipeForItems(items, { tokenId, createdBy }) {
  const usage = new Map();
  for (const item of items) {
    const recipe = item.product?.recipe || [];
    for (const line of recipe) {
      const ingId = String(line.ingredient);
      usage.set(ingId, (usage.get(ingId) || 0) + line.qty * item.qty);
    }
  }

  for (const [ingredientId, qty] of usage.entries()) {
    const ingredient = await Ingredient.findById(ingredientId);
    if (!ingredient) continue;
    ingredient.stockQty += qty;
    await ingredient.save();
    await StockLog.create({
      ingredient: ingredient._id,
      type: 'restock',
      qtyChange: qty,
      token: tokenId,
      createdBy,
    });
  }
}
