import Ingredient from '../models/Ingredient.js';
import StockLog from '../models/StockLog.js';
import PurchaseOrder from '../models/PurchaseOrder.js';
import Business from '../models/Business.js';
import { getEffectiveRecipe } from './menuService.js';
import { toStockQty } from '../utils/unitConversion.js';

// Deducts the ingredients consumed by a sold order's items (per each
// product's effective recipe, accounting for combos/customisations) and
// auto-creates a purchase order for any ingredient that drops below its
// reorder threshold as a result. Returns the names of any ingredients that
// were oversold (stock would have gone negative) so callers can flag the
// order for review instead of blocking it - this happens when an offline
// device sells more of an ingredient than was actually left.
export async function consumeRecipeForItems(items, { businessId, tokenId, createdBy }) {
  const business = await Business.findById(businessId);
  const autoCreatePO = business?.settings?.autoCreatePurchaseOrder ?? true;

  // items: each with product (populated, comboItems.product populated) and qty/selectedOptions
  const usage = new Map(); // ingredientId -> recipe-unit qty consumed

  for (const item of items) {
    if (!item.product) continue;
    const recipe = getEffectiveRecipe(item.product, item.selectedOptions || []);
    for (const line of recipe) {
      const ingId = String(line.ingredient);
      usage.set(ingId, (usage.get(ingId) || 0) + line.qty * item.qty);
    }
  }

  const oversoldIngredients = [];

  for (const [ingredientId, recipeQtyUsed] of usage.entries()) {
    const ingredient = await Ingredient.findById(ingredientId);
    if (!ingredient) continue;

    const qtyUsed = toStockQty(ingredient.unit, recipeQtyUsed);
    if (qtyUsed > ingredient.stockQty) oversoldIngredients.push(ingredient.name);
    ingredient.stockQty = Math.max(0, ingredient.stockQty - qtyUsed);
    await ingredient.save();

    await StockLog.create({
      ingredient: ingredient._id,
      type: 'consumption',
      qtyChange: -qtyUsed,
      token: tokenId,
      createdBy,
    });

    if (autoCreatePO && ingredient.stockQty <= ingredient.thresholdQty) {
      const existingPending = await PurchaseOrder.findOne({
        ingredient: ingredient._id,
        status: 'pending',
        autoGenerated: true,
      });
      if (!existingPending) {
        await PurchaseOrder.create({
          ingredient: ingredient._id,
          qtyOrdered: ingredient.reorderQty || ingredient.thresholdQty * 2 || 1,
          autoGenerated: true,
          createdBy,
        });
      }
    }
  }

  return oversoldIngredients;
}

// Restores stock when an order is cancelled before the kitchen has consumed
// the ingredients in any irreversible way (best-effort, mirrors the deduction).
export async function restockRecipeForItems(items, { tokenId, createdBy }) {
  const usage = new Map();
  for (const item of items) {
    if (!item.product) continue;
    const recipe = getEffectiveRecipe(item.product, item.selectedOptions || []);
    for (const line of recipe) {
      const ingId = String(line.ingredient);
      usage.set(ingId, (usage.get(ingId) || 0) + line.qty * item.qty);
    }
  }

  for (const [ingredientId, recipeQty] of usage.entries()) {
    const ingredient = await Ingredient.findById(ingredientId);
    if (!ingredient) continue;
    const qty = toStockQty(ingredient.unit, recipeQty);
    ingredient.stockQty += qty;
    await ingredient.save();
    await StockLog.create({
      ingredient: ingredient._id,
      type: 'restock',
      qtyChange: qty,
      token: tokenId,
      createdBy,
    });
  }
}
