import Outlet from '../models/Outlet.js';
import Ingredient from '../models/Ingredient.js';
import StockBatch from '../models/StockBatch.js';
import StockLog from '../models/StockLog.js';
import PurchaseOrder from '../models/PurchaseOrder.js';
import Expense from '../models/Expense.js';
import Notification from '../models/Notification.js';
import { runWithTenant } from '../utils/tenantContext.js';

function round3(n) {
  return Math.round(n * 1000) / 1000;
}

// Runs outside of any HTTP request, so tenantPlugin/outletPlugin don't
// auto-scope queries — we scope explicitly per outlet via runWithTenant so
// every PurchaseOrder/Expense/Notification created lands on the right tenant.
export async function runExpiryChecks() {
  const outlets = await Outlet.find({});
  for (const outlet of outlets) {
    await runWithTenant(outlet.businessId, outlet._id, async () => {
      await raisePoForExpiringSoon();
      await removeExpiredStock();
    });
  }
}

// If stock on hand will expire within 24h and there's no pending order for
// that ingredient already, get ahead of the gap by raising one now.
async function raisePoForExpiringSoon() {
  const in24h = new Date(Date.now() + 24 * 60 * 60 * 1000);
  const batches = await StockBatch.find({
    qty: { $gt: 0 },
    expiryDate: { $ne: null, $lte: in24h, $gte: new Date() },
  });

  const seen = new Set();
  for (const batch of batches) {
    const ingredientId = String(batch.ingredient);
    if (seen.has(ingredientId)) continue;
    seen.add(ingredientId);

    const existingPending = await PurchaseOrder.findOne({ ingredient: ingredientId, status: 'pending' });
    if (existingPending) continue;

    const ingredient = await Ingredient.findById(ingredientId);
    if (!ingredient) continue;

    await PurchaseOrder.create({
      ingredient: ingredientId,
      qtyOrdered: ingredient.reorderQty || ingredient.thresholdQty * 2 || 1,
      autoGenerated: true,
      requestedReason: 'Auto: current stock expires within 24h',
    });
  }
}

// Stock past its expiry is worthless — pull it out of the running total,
// book it as a wastage expense, and tell the people who can act on it.
async function removeExpiredStock() {
  const expiredBatches = await StockBatch.find({ qty: { $gt: 0 }, expiryDate: { $ne: null, $lt: new Date() } });

  for (const batch of expiredBatches) {
    const ingredient = await Ingredient.findById(batch.ingredient);
    if (!ingredient) continue;

    const removedQty = Math.min(batch.qty, ingredient.stockQty);
    if (removedQty <= 0) {
      batch.qty = 0;
      await batch.save();
      continue;
    }

    ingredient.stockQty = round3(ingredient.stockQty - removedQty);
    await ingredient.save();

    batch.qty = round3(batch.qty - removedQty);
    await batch.save();

    await StockLog.create({
      ingredient: ingredient._id,
      type: 'adjustment',
      qtyChange: -removedQty,
      reason: 'Expired — auto removed',
    });

    await Expense.create({
      category: 'wastage',
      amount: round3(removedQty * ingredient.costPerUnit),
      description: `Expired stock removed — ${ingredient.name} (${removedQty} ${ingredient.unit})`,
      ingredient: ingredient._id,
    });

    await Notification.create({
      type: 'expired_stock',
      message: `${removedQty} ${ingredient.unit} of ${ingredient.name} expired and was removed from stock.`,
      roles: ['owner', 'pos_manager'],
    });
  }
}
