import mongoose from 'mongoose';
import { nextSequence } from './Counter.js';
import tenantPlugin from '../utils/tenantPlugin.js';
import outletPlugin from '../utils/outletPlugin.js';

const purchaseOrderSchema = new mongoose.Schema(
  {
    poCode: String,
    ingredient: { type: mongoose.Schema.Types.ObjectId, ref: 'Ingredient', required: true },
    qtyOrdered: { type: Number, required: true },
    unitPrice: { type: Number }, // expected cost per unit, for budgeting
    status: { type: String, enum: ['pending', 'received', 'cancelled'], default: 'pending' },
    autoGenerated: { type: Boolean, default: false },
    receivedAt: Date,
    receivedQty: { type: Number },
    pricePerUnit: { type: Number }, // actual price paid per unit, captured on receive
    expiryDate: Date, // expiry of the received batch, if known
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    // Set when a pos_manager raises this PO as an ingredient request rather
    // than an owner ordering ahead of a threshold breach.
    requestedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    requestedReason: String,
  },
  { timestamps: true }
);

purchaseOrderSchema.pre('save', async function (next) {
  if (!this.poCode) {
    const seq = await nextSequence('purchase_order');
    this.poCode = `PO-${String(seq).padStart(5, '0')}`;
  }
  next();
});

purchaseOrderSchema.plugin(tenantPlugin);
purchaseOrderSchema.plugin(outletPlugin);

export default mongoose.model('PurchaseOrder', purchaseOrderSchema);
