import mongoose from 'mongoose';
import { nextSequence } from './Counter.js';
import tenantPlugin from '../utils/tenantPlugin.js';
import outletPlugin from '../utils/outletPlugin.js';

const purchaseOrderSchema = new mongoose.Schema(
  {
    poCode: String,
    ingredient: { type: mongoose.Schema.Types.ObjectId, ref: 'Ingredient', required: true },
    qtyOrdered: { type: Number, required: true },
    status: { type: String, enum: ['pending', 'received', 'cancelled'], default: 'pending' },
    autoGenerated: { type: Boolean, default: false },
    receivedAt: Date,
    createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { timestamps: true }
);

purchaseOrderSchema.pre('save', async function (next) {
  if (!this.poCode) {
    const seq = await nextSequence('purchase_order');
    this.poCode = `PO-${String(seq).padStart(5, '0')}`;
  }
  next();
});

purchaseOrderSchema.plugin(tenantPlugin);
purchaseOrderSchema.plugin(outletPlugin);

export default mongoose.model('PurchaseOrder', purchaseOrderSchema);
